name: Trigger Libraries

on:
  push:
    branches: [gh-pages, update-trigger-lib]
#    paths: 'package_adafruit_index.json'
  repository_dispatch:

jobs:
  trigger-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Script
      env:
        GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        # sorted alphabetically
        libs='Adafruit_ADS1X15
              Adafruit_ADXL343'
        for lib in $libs
        do
          echo "Triggering $lib"
          gh api repos/adafruit/$lib/dispatches -f event_type='rebuild by arduino-board-index'
          # sleep a bit to prevent CI overflow
          #sleep 60
        done
