name: Trigger Libraries

on:
  push:
    branches: [gh-pages, update-trigger-lib]
#    paths: 'package_adafruit_index.json'

jobs:
  trigger-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Script
      env:
        GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        # Enable repo scope for repository_dispatch permission
        gh auth refresh -h github.com -s repo
        #libs='Adafruit_ADS1X15 Adafruit_ADXL343'
        libs='Adafruit_ADXL343'
        for l in $libs
        do
          gh api repos/adafruit/$1/dispatches -f event_type='rebuild by arduino-board-index'
        done
