name: Trigger Libraries

on:
  push:
    branches: [gh-pages, update-trigger-lib]
#    paths: 'package_adafruit_index.json'

jobs:
  trigger-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Script
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        gh release list
        libs='Adafruit_ADS1X15 Adafruit_ADXL343'
        for l in $libs
        do
          echo $l
        done
