name: Trigger Libraries

on:
  push:
    branches: gh-pages
    paths: 'package_adafruit_index.json'
  workflow_dispatch:
    inputs:
      reason:
        type: string

jobs:
  trigger-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Script
      env:
        GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        # sorted alphabetically
        reason="${{ github.event.inputs.reason }}"
        echo input reason = $reason
        [[ -z "$reason" ]] && reason="rebuild by Adafruit SAMD/nRF new release"
        echo var reason = $reason
        libs='Adafruit_ADS1X15
              Adafruit_ADXL343'
        for lib in $libs
        do
          echo "Triggering $lib"
          gh api repos/adafruit/$lib/dispatches -f event_type="$reason"
          # sleep a bit to prevent CI overflow
          #sleep 60
        done
