name: Watch Arduino-ESP32

on:
  schedule:
    - cron: '*/10 * * * *'
  push:

jobs:
  trigger-libraries:
    runs-on: ubuntu-latest
    steps:
    - name: Get arduino-esp32 release
      env:
        GH_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
      run: |
        date
